//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenoMpie.Common.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VenoMpie.Common.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;results&quot;:[{&quot;release&quot;:&quot;(deborah_harry)-i_want_that_man_2000_cd_perplexer-bmi&quot;,&quot;date&quot;:&quot;2015-09-28 19:50:02&quot;,&quot;hasNFO&quot;:&quot;yes&quot;,&quot;hasSRS&quot;:&quot;yes&quot;},{&quot;release&quot;:&quot;2Pac-Rap_Phenomenon_II_(Mixed_By_DJ_Vlad_Dirty_Harry_And_DJ_Green_Lantern)-2003-EAC&quot;,&quot;date&quot;:&quot;2013-12-24 13:08:23&quot;,&quot;hasNFO&quot;:&quot;yes&quot;,&quot;hasSRS&quot;:&quot;yes&quot;},{&quot;release&quot;:&quot;3rd_Rock_From_The_Sun.3x26.The_Tooth_Harry.DVDRip_XviD-FoV&quot;,&quot;date&quot;:&quot;2011-07-05 00:00:00&quot;,&quot;hasNFO&quot;:&quot;yes&quot;,&quot;hasSRS&quot;:&quot;yes&quot;},{&quot;release&quot;:&quot;50.Greatest.Harry.Potter.Moments.HDTV.XviD-LOCATiON&quot;,&quot;date&quot;:&quot;2011-10-23  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_SRRDB_MultiResult {
            get {
                return ResourceManager.GetString("Interfaces_SRRDB_MultiResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;results&quot;:[{&quot;release&quot;:&quot;Harry.Potter.And.The.Chamber.Of.Secrets.2002.DVDRip.XViD-iNTERNAL-TDF&quot;,&quot;date&quot;:&quot;2011-07-11 00:00:00&quot;,&quot;hasNFO&quot;:&quot;yes&quot;,&quot;hasSRS&quot;:&quot;yes&quot;}],&quot;resultsCount&quot;:&quot;1&quot;,&quot;warnings&quot;:[],&quot;query&quot;:[&quot;Harry.Potter.And.The.Chamber.Of.Secrets.2002.DVDRip.XViD-iNTERNAL-TDF&quot;]}.
        /// </summary>
        internal static string Interfaces_SRRDB_SingleResult {
            get {
                return ResourceManager.GetString("Interfaces_SRRDB_SingleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Data&gt;
        ///	&lt;baseImgUrl&gt;http://thegamesdb.net/banners/&lt;/baseImgUrl&gt;
        ///	&lt;Images&gt;
        ///		&lt;fanart&gt;
        ///			&lt;original width=&quot;1920&quot; height=&quot;1080&quot;&gt;fanart/original/2-1.jpg&lt;/original&gt;
        ///			&lt;thumb&gt;fanart/thumb/2-1.jpg&lt;/thumb&gt;
        ///		&lt;/fanart&gt;
        ///		&lt;fanart&gt;
        ///			&lt;original width=&quot;1920&quot; height=&quot;1080&quot;&gt;fanart/original/2-2.jpg&lt;/original&gt;
        ///			&lt;thumb&gt;fanart/thumb/2-2.jpg&lt;/thumb&gt;
        ///		&lt;/fanart&gt;
        ///		&lt;fanart&gt;
        ///			&lt;original width=&quot;1920&quot; height=&quot;1080&quot;&gt;fanart/original/2-3.jpg&lt;/original&gt;
        ///			&lt;thumb&gt;fanart/thumb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_TheGamesDB_GetArt {
            get {
                return ResourceManager.GetString("Interfaces_TheGamesDB_GetArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data&gt;
        ///	&lt;baseImgUrl&gt;http://thegamesdb.net/banners/&lt;/baseImgUrl&gt;
        ///	&lt;Game&gt;
        ///		&lt;id&gt;2&lt;/id&gt;
        ///		&lt;GameTitle&gt;Crysis&lt;/GameTitle&gt;
        ///		&lt;PlatformId&gt;1&lt;/PlatformId&gt;
        ///		&lt;Platform&gt;PC&lt;/Platform&gt;
        ///		&lt;ReleaseDate&gt;11/13/2007&lt;/ReleaseDate&gt;
        ///		&lt;Overview&gt;
        ///From the makers of Far Cry, Crysis offers FPS fans the best-looking, most highly-evolving gameplay, requiring the player to use adaptive tactics and total customization of weapons and armor to survive in dynamic, hostile environments including Zero-G. Earth, 2019. A team of US  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_TheGamesDB_GetGame {
            get {
                return ResourceManager.GetString("Interfaces_TheGamesDB_GetGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Data&gt;
        ///  &lt;Game&gt;
        ///    &lt;id&gt;14728&lt;/id&gt;
        ///    &lt;GameTitle&gt;Street Rod&lt;/GameTitle&gt;
        ///    &lt;ReleaseDate&gt;01/01/1989&lt;/ReleaseDate&gt;
        ///    &lt;Platform&gt;PC&lt;/Platform&gt;
        ///  &lt;/Game&gt;
        ///  &lt;Game&gt;
        ///    &lt;id&gt;14730&lt;/id&gt;
        ///    &lt;GameTitle&gt;Street Rod 2: The Next Generation&lt;/GameTitle&gt;
        ///    &lt;ReleaseDate&gt;01/01/1991&lt;/ReleaseDate&gt;
        ///    &lt;Platform&gt;PC&lt;/Platform&gt;
        ///  &lt;/Game&gt;
        ///  &lt;Game&gt;
        ///    &lt;id&gt;24117&lt;/id&gt;
        ///    &lt;GameTitle&gt;Rod Land&lt;/GameTitle&gt;
        ///    &lt;ReleaseDate&gt;04/01/1990&lt;/ReleaseDate&gt;
        ///    &lt;Platform&gt;Nintendo G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_TheGamesDB_GetGamesList {
            get {
                return ResourceManager.GetString("Interfaces_TheGamesDB_GetGamesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Data&gt;
        ///	&lt;baseImgUrl&gt;http://thegamesdb.net/banners/&lt;/baseImgUrl&gt;
        ///	&lt;Platform&gt;
        ///		&lt;id&gt;15&lt;/id&gt;
        ///		&lt;Platform&gt;Microsoft Xbox 360&lt;/Platform&gt;
        ///		&lt;console&gt;http://www.youtube.com/watch?v=15.png&lt;/console&gt;
        ///		&lt;controller&gt;http://www.youtube.com/watch?v=15.png&lt;/controller&gt;
        ///		&lt;overview&gt;The Xbox 360 is the second video game console produced by Microsoft and the successor to the Xbox. The Xbox 360 competes with Sony&amp;amp;#039;s PlayStation 3 and Nintendo&amp;amp;#039;s Wii as part of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_TheGamesDB_GetPlatform {
            get {
                return ResourceManager.GetString("Interfaces_TheGamesDB_GetPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///
        ///&lt;Data&gt;
        ///	&lt;basePlatformUrl&gt;http://thegamesdb.net/platform/&lt;/basePlatformUrl&gt;
        ///	&lt;Platforms&gt;
        ///		&lt;Platform&gt;
        ///			&lt;id&gt;25&lt;/id&gt;
        ///			&lt;name&gt;3DO&lt;/name&gt;
        ///			&lt;alias&gt;3do&lt;/alias&gt;
        ///		&lt;/Platform&gt;
        ///		&lt;Platform&gt;
        ///			&lt;id&gt;4944&lt;/id&gt;
        ///			&lt;name&gt;Acorn Archimedes&lt;/name&gt;
        ///			&lt;alias&gt;acorn-archimedes&lt;/alias&gt;
        ///		&lt;/Platform&gt;
        ///		&lt;Platform&gt;
        ///			&lt;id&gt;4911&lt;/id&gt;
        ///			&lt;name&gt;Amiga&lt;/name&gt;
        ///			&lt;alias&gt;amiga&lt;/alias&gt;
        ///		&lt;/Platform&gt;
        ///		&lt;Platform&gt;
        ///			&lt;id&gt;4947&lt;/id&gt;
        ///			&lt;name&gt;Amiga CD32&lt;/name&gt;
        ///			&lt;alias&gt;amiga-c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_TheGamesDB_GetPlatformList {
            get {
                return ResourceManager.GetString("Interfaces_TheGamesDB_GetPlatformList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;size&quot;:7857,&quot;type&quot;:&quot;PWAD&quot;,&quot;iwad&quot;:&quot;DOOM2&quot;,&quot;port&quot;:[&quot;DOOM2&quot;],&quot;filenames&quot;:[&quot;barbell.wad&quot;],&quot;links&quot;:[&quot;http:\/\/autokrator.butanpressfight.com\/Doom%20Junk\/D!ZONE%203\/WADS\/DOOM2\/BARBELL.WAD&quot;]}].
        /// </summary>
        internal static string Interfaces_WadArchive_Barbell_Wadseeker {
            get {
                return ResourceManager.GetString("Interfaces_WadArchive_Barbell_Wadseeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;md5&quot;:&quot;333ca955620fd1678619e62976fb96bb&quot;,&quot;sha1&quot;:&quot;6a92d2228bf609296b6899fed6f7e2bae55f64b0&quot;,&quot;size&quot;:2109396,&quot;type&quot;:&quot;PWAD&quot;,&quot;iwad&quot;:&quot;DOOM2&quot;,&quot;port&quot;:&quot;DOOM2&quot;,&quot;filenames&quot;:[&quot;dwango5.wad&quot;,&quot;faked5.wad&quot;],&quot;links&quot;:[&quot;http:\/\/britishgangsterfilms.com\/wads\/dwango5.wad&quot;,&quot;http:\/\/content.wuala.com\/contents\/darklord328\/darklordswadfiles\/dwango5.wad&quot;,&quot;http:\/\/crimson.lostsig.net\/doom\/wads\/DWANGO5.WAD&quot;,&quot;http:\/\/files.funcrusher.net\/wads\/dwango5.zip&quot;,&quot;http:\/\/grandpachuck.org\/files\/wads\/dwango5.wad&quot;,&quot;http:\/\/g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_WadArchive_Dwango5_Latest {
            get {
                return ResourceManager.GetString("Interfaces_WadArchive_Dwango5_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;size&quot;:2109396,&quot;type&quot;:&quot;PWAD&quot;,&quot;iwad&quot;:&quot;DOOM2&quot;,&quot;port&quot;:[&quot;DOOM2&quot;],&quot;filenames&quot;:[&quot;dwango5.wad&quot;,&quot;faked5.wad&quot;],&quot;links&quot;:[&quot;http:\/\/britishgangsterfilms.com\/wads\/dwango5.wad&quot;,&quot;http:\/\/content.wuala.com\/contents\/darklord328\/darklordswadfiles\/dwango5.wad&quot;,&quot;http:\/\/crimson.lostsig.net\/doom\/wads\/DWANGO5.WAD&quot;,&quot;http:\/\/files.funcrusher.net\/wads\/dwango5.zip&quot;,&quot;http:\/\/grandpachuck.org\/files\/wads\/dwango5.wad&quot;,&quot;http:\/\/grandvoid.sickedwick.net\/wads\/dwango5.zip&quot;,&quot;http:\/\/huntsvegas.org\/files\/wads\/DWANG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_WadArchive_Dwango5_Wadseeker {
            get {
                return ResourceManager.GetString("Interfaces_WadArchive_Dwango5_Wadseeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;status&quot;: &quot;ok&quot;,
        ///	&quot;status_message&quot;: &quot;Query was successful&quot;,
        ///	&quot;data&quot;: {
        ///		&quot;movie_count&quot;: 6393,
        ///		&quot;limit&quot;: 20,
        ///		&quot;page_number&quot;: 1,
        ///		&quot;movies&quot;: [{
        ///			&quot;id&quot;: 6737,
        ///			&quot;url&quot;: &quot;https:\/\/yts.ag\/movie\/pirates-of-the-caribbean-dead-men-tell-no-tales-2017&quot;,
        ///			&quot;imdb_code&quot;: &quot;tt1790809&quot;,
        ///			&quot;title&quot;: &quot;Pirates of the Caribbean: Dead Men Tell No Tales&quot;,
        ///			&quot;title_english&quot;: &quot;Pirates of the Caribbean: Dead Men Tell No Tales&quot;,
        ///			&quot;title_long&quot;: &quot;Pirates of the Caribbean: Dead Men Tell No Tales (2017)&quot;,
        ///			&quot;slug&quot;: &quot;pirates [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_YTS_List_Movies {
            get {
                return ResourceManager.GetString("Interfaces_YTS_List_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;status&quot;: &quot;ok&quot;,
        ///	&quot;status_message&quot;: &quot;Query was successful&quot;,
        ///	&quot;data&quot;: {
        ///		&quot;movie_count&quot;: 4,
        ///		&quot;movies&quot;: [{
        ///			&quot;id&quot;: 349,
        ///			&quot;url&quot;: &quot;https:\/\/yts.ag\/movie\/babylon-a-d-2008&quot;,
        ///			&quot;imdb_code&quot;: &quot;tt0364970&quot;,
        ///			&quot;title&quot;: &quot;Babylon A.D.&quot;,
        ///			&quot;title_english&quot;: &quot;Babylon A.D.&quot;,
        ///			&quot;title_long&quot;: &quot;Babylon A.D. (2008)&quot;,
        ///			&quot;slug&quot;: &quot;babylon-a-d-2008&quot;,
        ///			&quot;year&quot;: 2008,
        ///			&quot;rating&quot;: 5.6,
        ///			&quot;runtime&quot;: 101,
        ///			&quot;genres&quot;: [&quot;Action&quot;,
        ///			&quot;Adventure&quot;,
        ///			&quot;Sci-Fi&quot;,
        ///			&quot;Thriller&quot;],
        ///			&quot;summary&quot;: &quot;In a near future, the mercenary T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interfaces_YTS_Movie_Suggestions {
            get {
                return ResourceManager.GetString("Interfaces_YTS_Movie_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_ClrMameProNES {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_ClrMameProNES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_ClrMameProNESXML {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_ClrMameProNESXML", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_ClrMemeProNESFull {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_ClrMemeProNESFull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_ClrMemeProNESFullXML {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_ClrMemeProNESFullXML", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_RAR_128D_RR_Comment {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_RAR_128D_RR_Comment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_RAR_512D_Comment {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_RAR_512D_Comment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_RAR_512D_Comment_NoCompression {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_RAR_512D_Comment_NoCompression", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_RAR_512D_Comment_NormalCompression {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_RAR_512D_Comment_NormalCompression", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_RAR_512D_Comment_Password {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_RAR_512D_Comment_Password", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_RAR_Best_4096D_Solid {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_RAR_Best_4096D_Solid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_SFVFile {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_SFVFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_TDC {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_TDC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_TDCFull {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_TDCFull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IO_FileReaders_TDCMaster {
            get {
                object obj = ResourceManager.GetObject("IO_FileReaders_TDCMaster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;warezcol.css&quot;&gt;&lt;style&gt; .list { font-size: 16px; font-family: &quot;Moder DOS 437&quot;; color: white; line-height: 15px;} body { background-color: black; }&lt;/style&gt;&lt;script&gt;   (function(i,s,o,g,r,a,m){i[&apos;GoogleAnalyticsObject&apos;]=r;i[r]=i[r]||function(){   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)   })(window,document,&apos;script&apos;,&apos;// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scrapers_SCiZE_List {
            get {
                return ResourceManager.GetString("Scrapers_SCiZE_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Traz
        ///Author Jeroen Kimmel (Red)
        ///Released 1988 Cascade Games
        ///Load Address $1000
        ///Number of tunes 27
        ///Init Address $17F4
        ///Default tune 1
        ///Play Address $17F7
        ///Speed $00000000
        ///SID Model 6581
        ///Clock PAL
        ///File Format PSID
        ///BASIC FALSE
        ///Format Version 2
        ///PlaySID Specific FALSE
        ///Free Pages $2000 - $68ff
        ///MD5 e0df2be10e67a7a5059e6d36223a5bb1.
        /// </summary>
        internal static string Sid_Details {
            get {
                return ResourceManager.GetString("Sid_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Traz {
            get {
                object obj = ResourceManager.GetObject("Traz", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
